"""Shared application services used by the CLI, the Python API, and the future local server."""

from __future__ import annotations

from .datasets import (
    DATASET_COLUMN_ROLES,
    DATASET_READER_SCHEMA_VERSION,
    DatasetReadError,
    DatasetRow,
    plan_dataset_batches,
    project_dataset_rows,
    read_dataset_rows,
    resolve_dataset_location,
    validate_column_mapping,
)
from .hub import (
    HUB_SEARCH_SCHEMA_VERSION,
    HubSearchEntry,
    HubSearchError,
    search_hub,
)
from .model_resolution import (
    HUB_RESOLUTION_SCHEMA_VERSION,
    HUGGINGFACE_API_ORIGIN,
    ModelResolutionError,
    resolve_huggingface_dataset_revision,
    resolve_huggingface_plan,
    resolve_huggingface_revision,
)
from .retention import (
    RETENTION_SCHEMA_VERSION,
    RetentionError,
    RetentionPolicy,
    RetentionReport,
    evaluate_retention,
)
from .run_engine import (
    EXECUTION_PROGRESS_STAGE,
    ROW_FAILURE_KINDS,
    RUN_ENGINE_SCHEMA_VERSION,
    ExecutionOutcome,
    RowFailure,
    RowRecord,
    RowResult,
    RunEngineError,
    execute_row_schedule,
)
from .run_inputs import (
    RUN_INPUTS_SCHEMA_VERSION,
    RunInputError,
    plan_input_batches,
    prepare_input_rows,
    prepare_prompt_rows,
)
from .run_service import (
    CHECKPOINT_MANIFEST_TYPE,
    CHECKPOINT_SCHEMA_VERSION,
    RUN_SERVICE_SCHEMA_VERSION,
    RunCheckpoint,
    RunExecutionReport,
    RunServiceError,
    build_initial_record,
    derive_run_failure,
    execute_specification,
    load_checkpoint,
    publish_run_report,
)
from .workspace import (
    WorkspaceSnapshot,
    initialize_workspace,
    open_workspace,
    query_runs,
    record_run_record,
    register_run,
    sync_runs_from_shards,
)

__all__ = [
    "CHECKPOINT_MANIFEST_TYPE",
    "CHECKPOINT_SCHEMA_VERSION",
    "DATASET_COLUMN_ROLES",
    "DATASET_READER_SCHEMA_VERSION",
    "HUB_SEARCH_SCHEMA_VERSION",
    "HUB_RESOLUTION_SCHEMA_VERSION",
    "HUGGINGFACE_API_ORIGIN",
    "EXECUTION_PROGRESS_STAGE",
    "ROW_FAILURE_KINDS",
    "RUN_ENGINE_SCHEMA_VERSION",
    "RUN_INPUTS_SCHEMA_VERSION",
    "RUN_SERVICE_SCHEMA_VERSION",
    "DatasetReadError",
    "RETENTION_SCHEMA_VERSION",
    "RetentionError",
    "RetentionReport",
    "RetentionPolicy",
    "evaluate_retention",
    "DatasetRow",
    "HubSearchEntry",
    "HubSearchError",
    "ModelResolutionError",
    "ExecutionOutcome",
    "RowFailure",
    "RowRecord",
    "RowResult",
    "RunCheckpoint",
    "RunEngineError",
    "RunExecutionReport",
    "RunInputError",
    "RunServiceError",
    "WorkspaceSnapshot",
    "build_initial_record",
    "derive_run_failure",
    "execute_row_schedule",
    "execute_specification",
    "initialize_workspace",
    "load_checkpoint",
    "open_workspace",
    "plan_dataset_batches",
    "plan_input_batches",
    "prepare_input_rows",
    "prepare_prompt_rows",
    "project_dataset_rows",
    "publish_run_report",
    "query_runs",
    "read_dataset_rows",
    "record_run_record",
    "register_run",
    "resolve_dataset_location",
    "search_hub",
    "resolve_huggingface_dataset_revision",
    "resolve_huggingface_plan",
    "resolve_huggingface_revision",
    "sync_runs_from_shards",
    "validate_column_mapping",
]
