"""Validated instance/custom execution and lazy optional model loading.

HF/local calls import optional model packages only after explicit immutable
resolution and policy preflight. Real checkpoint, cache, GPU, and fidelity
validation remains deferred to the model-validation ledger and final VM.
`load_and_scan()` composes those resolved HF/local loaders with static
discovery after which cleanup succeeds; it does not add inference or CLI
loading.
"""

from .capabilities import (
    ROUTING_DECODE_CAPABILITY_SCHEMA_VERSION,
    RouterPayloadShape,
    RoutingDecodeCapability,
    RoutingDecodeError,
    RoutingHookDecoder,
    ScoreSemantics,
    TokenSequencePolicy,
    native_id_map,
    validate_decoded_routing,
    validate_observed_routing,
)
from .capture_support import (
    CaptureSupportGrade,
    CaptureSupportReport,
    classify_capture_support,
)
from .compatibility import (
    APPROVED_COMPATIBILITY_BRIDGES,
    COMPATIBILITY_SCHEMA_VERSION,
    TORCH_FX_AVAILABLE_BRIDGE,
    CompatibilityBridge,
    HardwareFingerprint,
    ModelRuntimeMetadata,
    RuntimeCompatibilityError,
    RuntimeProfile,
    RuntimeProfileCacheKey,
    RuntimeProfileSelection,
    RuntimeRequirements,
    RuntimeSelectionStatus,
    package_name,
    preflight_runtime,
    resolve_runtime_profile,
    select_runtime_profile,
    version_satisfies,
)
from .contracts import (
    CleanupCallback,
    CleanupError,
    CustomLoaderExecutionError,
    LoadedModel,
    LoadResult,
    ModelLoadError,
    ModelObservationError,
    ModelRuntimeDependencyError,
    PendingRuntimeCleanup,
    RuntimeArtifacts,
    RuntimeCleanupError,
    RuntimeLoadError,
    RuntimeObservation,
    RuntimeValidationError,
)
from .dependency_preflight import (
    DEPENDENCY_PREFLIGHT_SCHEMA_VERSION,
    DependencyCheck,
    DependencyPreflightError,
    DependencyRequirementState,
    DependencyStatus,
    RuntimeDependencyInventory,
    RuntimeDependencyPreflight,
    check_declared_dependencies,
    preflight_runtime_dependencies,
)
from .generic_capture import (
    StructuredCaptureError,
    StructuredExpertTarget,
    StructuredRouterTarget,
    StructuredRoutingForwardResult,
    decode_expert_activity,
    decode_structured_payload,
    run_structured_expert_forward,
    run_structured_routing_forward,
    structured_expert_targets,
    structured_router_targets,
)
from .loader import load_custom, load_instance
from .mixtral_routing import MixtralRoutingDecoder
from .model_loader import load_huggingface, load_local
from .prompt_prefill import MixtralPromptPrefillError, run_mixtral_prompt_prefill
from .qualification import (
    RUNTIME_QUALIFICATION_SCHEMA_VERSION,
    RuntimeQualification,
    RuntimeQualificationError,
    qualify_huggingface_runtime,
)
from .qwen3_5_routing import Qwen3_5RoutingDecoder
from .resource_admission import (
    RESOURCE_ADMISSION_SCHEMA_VERSION,
    ResourceAdmission,
    ResourceAdmissionError,
    ResourceAdmissionStatus,
    ResourceSnapshot,
    admit_huggingface_model,
    cached_snapshot_bytes,
    estimate_hub_checkpoint_bytes,
    evaluate_resource_admission,
    observe_resource_snapshot,
)
from .routing import RoutingCaptureError, RoutingCaptureSession, RoutingCaptureTarget
from .routing_forward import (
    MixtralRoutingForwardResult,
    RoutingForwardResult,
    run_mixtral_routing_forward,
    run_qwen3_5_routing_forward,
    run_routing_forward,
)
from .scan import load_and_scan

__all__ = [
    "CleanupCallback",
    "CleanupError",
    "CaptureSupportGrade",
    "CaptureSupportReport",
    "APPROVED_COMPATIBILITY_BRIDGES",
    "COMPATIBILITY_SCHEMA_VERSION",
    "TORCH_FX_AVAILABLE_BRIDGE",
    "CompatibilityBridge",
    "HardwareFingerprint",
    "ModelRuntimeMetadata",
    "RuntimeCompatibilityError",
    "RuntimeProfile",
    "RuntimeProfileCacheKey",
    "RuntimeProfileSelection",
    "RuntimeRequirements",
    "RuntimeSelectionStatus",
    "package_name",
    "preflight_runtime",
    "resolve_runtime_profile",
    "select_runtime_profile",
    "version_satisfies",
    "ROUTING_DECODE_CAPABILITY_SCHEMA_VERSION",
    "RouterPayloadShape",
    "RoutingDecodeCapability",
    "RoutingDecodeError",
    "RoutingHookDecoder",
    "ScoreSemantics",
    "TokenSequencePolicy",
    "native_id_map",
    "validate_decoded_routing",
    "validate_observed_routing",
    "classify_capture_support",
    "CustomLoaderExecutionError",
    "LoadResult",
    "LoadedModel",
    "ModelLoadError",
    "ModelObservationError",
    "ModelRuntimeDependencyError",
    "MixtralRoutingDecoder",
    "MixtralRoutingForwardResult",
    "RoutingForwardResult",
    "MixtralPromptPrefillError",
    "Qwen3_5RoutingDecoder",
    "RUNTIME_QUALIFICATION_SCHEMA_VERSION",
    "RuntimeQualification",
    "RuntimeQualificationError",
    "qualify_huggingface_runtime",
    "run_qwen3_5_routing_forward",
    "PendingRuntimeCleanup",
    "RuntimeArtifacts",
    "RuntimeCleanupError",
    "RuntimeLoadError",
    "RuntimeObservation",
    "RuntimeValidationError",
    "RESOURCE_ADMISSION_SCHEMA_VERSION",
    "ResourceAdmission",
    "ResourceAdmissionError",
    "ResourceAdmissionStatus",
    "ResourceSnapshot",
    "admit_huggingface_model",
    "cached_snapshot_bytes",
    "estimate_hub_checkpoint_bytes",
    "evaluate_resource_admission",
    "observe_resource_snapshot",
    "DEPENDENCY_PREFLIGHT_SCHEMA_VERSION",
    "DependencyCheck",
    "DependencyPreflightError",
    "DependencyRequirementState",
    "DependencyStatus",
    "RuntimeDependencyInventory",
    "RuntimeDependencyPreflight",
    "check_declared_dependencies",
    "preflight_runtime_dependencies",
    "RoutingCaptureError",
    "RoutingCaptureSession",
    "RoutingCaptureTarget",
    "run_mixtral_routing_forward",
    "run_mixtral_prompt_prefill",
    "run_routing_forward",
    "StructuredCaptureError",
    "StructuredExpertTarget",
    "StructuredRoutingForwardResult",
    "StructuredRouterTarget",
    "decode_expert_activity",
    "decode_structured_payload",
    "run_structured_expert_forward",
    "run_structured_routing_forward",
    "structured_expert_targets",
    "structured_router_targets",
    "load_custom",
    "load_huggingface",
    "load_and_scan",
    "load_instance",
    "load_local",
]
