"""Local read-only server layer over shared application services."""

from __future__ import annotations

from .app import SERVER_SCHEMA_VERSION, ServerDependencyError, create_app
from .dto import (
    ActivityResponse,
    AdapterEntryResponse,
    AdaptersResponse,
    ArchitectureResponse,
    DiscoveryRequest,
    HealthResponse,
    HubSearchEntryResponse,
    HubSearchResponse,
    InterventionRecipeRequest,
    InterventionRecipeResponse,
    JobCreatedResponse,
    JobDiagnosticEntryResponse,
    JobDiagnosticsReference,
    JobDiagnosticsResponse,
    JobProgressResponse,
    JobResponse,
    RoutingShardEntryResponse,
    RunDetailResponse,
    RunEntryResponse,
    RunsResponse,
    RunStartRequest,
    RunSummaryResponse,
    WorkspaceResponse,
)

__all__ = [
    "SERVER_SCHEMA_VERSION",
    "ActivityResponse",
    "AdapterEntryResponse",
    "AdaptersResponse",
    "ArchitectureResponse",
    "DiscoveryRequest",
    "HealthResponse",
    "HubSearchEntryResponse",
    "HubSearchResponse",
    "InterventionRecipeRequest",
    "InterventionRecipeResponse",
    "JobCreatedResponse",
    "JobDiagnosticEntryResponse",
    "JobDiagnosticsReference",
    "JobDiagnosticsResponse",
    "JobProgressResponse",
    "JobResponse",
    "RoutingShardEntryResponse",
    "RunDetailResponse",
    "RunEntryResponse",
    "RunSummaryResponse",
    "RunStartRequest",
    "RunsResponse",
    "ServerDependencyError",
    "WorkspaceResponse",
    "create_app",
]
